spring.application.name=TiendaProject

server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/tienda_web_express


spring.datasource.username=postgres


spring.datasource.password=200419




spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect